version: '3'
services:
  sound-chain:
    build: .
    volumes:
      - .:/app/sound-chain
      - node_modules:/app/sound-chain/node_modules
    ports:
      - "3000:3000"      # React
      - "8545:8545"      # Ganache/Hardhat
    environment:
      - NODE_ENV=development
    command: /bin/bash
    stdin_open: true
    tty: true

volumes:
  node_modules: